# Generated by Django 3.2.8 on 2022-03-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default1.jpg', upload_to='tuition/images'),
        ),
    ]
