# Generated by Django 3.2.8 on 2022-03-04 03:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Arabic', 'Arabic'), ('Urdu', 'Urdu'), ('Hindi', 'Hindi')], default='Bangla', max_length=100),
        ),
    ]
