# Generated by Django 3.2.8 on 2022-03-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0010_auto_20220308_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(max_length=100),
        ),
    ]
