# Generated by Django 4.0.3 on 2022-03-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biodata',
            field=models.TextField(max_length=200),
        ),
    ]
